# Generated by Django 4.1.6 on 2024-01-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pest',
            old_name='loc',
            new_name='location',
        ),
        migrations.AddField(
            model_name='pest',
            name='img1',
            field=models.ImageField(default=1, upload_to='pest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pest',
            name='img2',
            field=models.ImageField(default=1, upload_to='pest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pest',
            name='img3',
            field=models.ImageField(default=1, upload_to='pest'),
            preserve_default=False,
        ),
    ]
