# Generated by Django 4.1.6 on 2024-01-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_loc_pest_location_pest_img1_pest_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='map',
            field=models.ImageField(default=1, upload_to='maps'),
            preserve_default=False,
        ),
    ]
